################################### Default Configuration ############################
baseurl = "https://www.liplus-research.com/"
languageCode = "en"
title = "LiPlus"
theme = "vex-hugo"

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
[[params.plugins.css]]
URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
URL = "https://fonts.googleapis.com/css?family=Roboto::300,400,600,700"
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/themefisher-fonts.css"
[[params.plugins.css]]
URL = "css/owl.carousel.css"
[[params.plugins.css]]
URL = "css/magnific-popup.css"
[[params.plugins.css]]
URL = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery-2.1.1.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/owl.carousel.min.js"
[[params.plugins.js]]
URL = "js/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.js"


###################################### Navigation ######################################

[[menu.main]]
name = "Services"
URL = "service"
weight = 2

[[menu.main]]
name = "The Team"
URL = "team"
weight = 3

[[menu.main]]
name = "Contact Us"
URL = "contact"
weight = 4

########################### Default parameters ##########################
[params]
logo = ""
home = "About"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
google_analitycs_id = "" # Your ID
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
# copyright
copyright = "Copyright 2020 &copy; LiPlus | Powered by [themefisher](http://www.Themefisher.com)."

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format